import Main from '@/components/Main';

export const metadata = {
  title: 'Main | RG',
  description: 'Generated by create next app.',
};

export default function Home(): JSX.Element {
  return (
    <>
      <Main />
    </>
  );
}
